import { fireEvent, render, screen } from '@testing-library/react-native';

import { CadastroAlunoProvisorioForm } from './CadastroAlunoProvisorioForm';

describe('CadastroAlunoProvisorioForm', () => {
  it('renders only the Nome field — identificador is generated by the system (issue #159)', async () => {
    await render(
      <CadastroAlunoProvisorioForm
        nome=""
        enviando={false}
        onChangeNome={jest.fn()}
        onSubmit={jest.fn()}
      />,
    );

    expect(screen.getByPlaceholderText('Nome do Aluno')).toBeTruthy();
    expect(screen.queryByPlaceholderText('Identificador (ex: número de matrícula)')).toBeNull();
  });

  it('calls onChangeNome when the Nome field changes', async () => {
    const onChangeNome = jest.fn();
    await render(
      <CadastroAlunoProvisorioForm
        nome=""
        enviando={false}
        onChangeNome={onChangeNome}
        onSubmit={jest.fn()}
      />,
    );

    await fireEvent.changeText(screen.getByPlaceholderText('Nome do Aluno'), 'João Pedro');

    expect(onChangeNome).toHaveBeenCalledWith('João Pedro');
  });

  it('calls onSubmit when Cadastrar is pressed', async () => {
    const onSubmit = jest.fn();
    await render(
      <CadastroAlunoProvisorioForm
        nome="João Pedro"
        enviando={false}
        onChangeNome={jest.fn()}
        onSubmit={onSubmit}
      />,
    );

    await fireEvent.press(screen.getByText('Cadastrar'));

    expect(onSubmit).toHaveBeenCalled();
  });

  it('shows a disabled sending state and the Api error message', async () => {
    await render(
      <CadastroAlunoProvisorioForm
        nome="João Pedro"
        erro="Não foi possível concluir a operação."
        enviando={true}
        onChangeNome={jest.fn()}
        onSubmit={jest.fn()}
      />,
    );

    expect(screen.getByText('Enviando...')).toBeTruthy();
    expect(screen.getByText('Não foi possível concluir a operação.')).toBeTruthy();
  });
});
