// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synclass.Infrastructure.Persistence;

#nullable disable

namespace Synclass.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SynclassDbContext))]
    [Migration("20260813234120_AdicionaLimiteAlunosHorario")]
    partial class AdicionaLimiteAlunosHorario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Synclass.Domain.Autenticacao.CodigoOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CodigosOtp", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Configuracoes.ConfiguracaoProfessor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeloAgendamento")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesProfessor", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Horarios.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("LimiteAlunos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId", "DiaSemana");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Matriculas.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlunoUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentificadorProvisorio")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NomeProvisorio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoUsuarioId");

                    b.HasIndex("ProfessorId", "IdentificadorProvisorio")
                        .IsUnique()
                        .HasFilter("\"IdentificadorProvisorio\" IS NOT NULL");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.PapelAtribuido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Papel")
                        .IsUnique();

                    b.ToTable("PapeisUsuario", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Contato")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Autenticacao.CodigoOtp", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Configuracoes.ConfiguracaoProfessor", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Horarios.Horario", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Matriculas.Matricula", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlunoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.PapelAtribuido", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany("Papeis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Papeis");
                });
#pragma warning restore 612, 618
        }
    }
}
