// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synclass.Infrastructure.Persistence;

#nullable disable

namespace Synclass.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SynclassDbContext))]
    [Migration("20260820092650_AdicionaCodigoConvite")]
    partial class AdicionaCodigoConvite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Synclass.Domain.Alocacoes.AlocacaoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrigemAlocacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.HasIndex("HorarioId", "MatriculaId")
                        .IsUnique();

                    b.ToTable("AlocacoesHorario", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Aulas.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("HorarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId", "Data")
                        .IsUnique();

                    b.ToTable("Aulas", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Aulas.CancelamentoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CanceladoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.HasIndex("AulaId", "MatriculaId")
                        .IsUnique();

                    b.ToTable("CancelamentosAula", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Autenticacao.CodigoOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CodigosOtp", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Cobrancas.RegraDeCobranca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("RegrasDeCobranca", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("RegraDeCobranca");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Synclass.Domain.Configuracoes.ConfiguracaoProfessor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModeloAgendamento")
                        .HasColumnType("integer");

                    b.Property<int>("PrazoCancelamentoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesProfessor", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Convites.Convite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("ContatoTipo")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MatriculaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UsadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo");

                    b.HasIndex("MatriculaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Convites", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Frequencias.RegistroFrequencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AulaId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ConfirmadoPeloAluno")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("uuid");

                    b.Property<int?>("StatusProfessor")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.HasIndex("AulaId", "MatriculaId")
                        .IsUnique();

                    b.ToTable("RegistrosFrequencia", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Horarios.Horario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("LimiteAlunos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoMarcacao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId", "DiaSemana");

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Matriculas.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlunoUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentificadorProvisorio")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("NomeProvisorio")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoUsuarioId");

                    b.HasIndex("ProfessorId", "IdentificadorProvisorio")
                        .IsUnique()
                        .HasFilter("\"IdentificadorProvisorio\" IS NOT NULL");

                    b.ToTable("Matriculas", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.PapelAtribuido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Papel")
                        .IsUnique();

                    b.ToTable("PapeisUsuario", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Contato")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Synclass.Domain.Cobrancas.RegraFixoMensal", b =>
                {
                    b.HasBaseType("Synclass.Domain.Cobrancas.RegraDeCobranca");

                    b.HasDiscriminator().HasValue("FixoMensal");
                });

            modelBuilder.Entity("Synclass.Domain.Cobrancas.RegraFixoPorAula", b =>
                {
                    b.HasBaseType("Synclass.Domain.Cobrancas.RegraDeCobranca");

                    b.HasDiscriminator().HasValue("FixoPorAula");
                });

            modelBuilder.Entity("Synclass.Domain.Cobrancas.RegraValorPorAula", b =>
                {
                    b.HasBaseType("Synclass.Domain.Cobrancas.RegraDeCobranca");

                    b.Property<int>("FrequenciaSemanalContratada")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("ValorPorAula");
                });

            modelBuilder.Entity("Synclass.Domain.Alocacoes.AlocacaoHorario", b =>
                {
                    b.HasOne("Synclass.Domain.Horarios.Horario", null)
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synclass.Domain.Matriculas.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Aulas.Aula", b =>
                {
                    b.HasOne("Synclass.Domain.Horarios.Horario", null)
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Aulas.CancelamentoAula", b =>
                {
                    b.HasOne("Synclass.Domain.Aulas.Aula", null)
                        .WithMany()
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synclass.Domain.Matriculas.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Autenticacao.CodigoOtp", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Cobrancas.RegraDeCobranca", b =>
                {
                    b.HasOne("Synclass.Domain.Matriculas.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Configuracoes.ConfiguracaoProfessor", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Convites.Convite", b =>
                {
                    b.HasOne("Synclass.Domain.Matriculas.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Frequencias.RegistroFrequencia", b =>
                {
                    b.HasOne("Synclass.Domain.Aulas.Aula", null)
                        .WithMany()
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synclass.Domain.Matriculas.Matricula", null)
                        .WithMany()
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Horarios.Horario", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Matriculas.Matricula", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AlunoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.PapelAtribuido", b =>
                {
                    b.HasOne("Synclass.Domain.Usuarios.Usuario", null)
                        .WithMany("Papeis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synclass.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Papeis");
                });
#pragma warning restore 612, 618
        }
    }
}
